const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
async function listRecords(db,type){const q=db.prepare("SELECT id, number, record_type, customer_name, phone, description, route, total, total_boxes, status, notes, created_at, updated_at FROM records WHERE record_type = ? ORDER BY created_at DESC").bind(type);return(await q.all()).results}
async function handleApi(request,env,url){
 try{
  const upload=url.pathname.match(/^\/api\/uploads\/([^/]+)$/);if(upload&&request.method==='PUT'){const type=request.headers.get('content-type')||'application/octet-stream';if(!type.startsWith('image/'))return json({error:'Solo se permiten imágenes'},400);const size=Number(request.headers.get('content-length')||0);if(size>5*1024*1024)return json({error:'La imagen supera 5 MB'},413);await env.BUCKET.put('products/'+upload[1],request.body,{httpMetadata:{contentType:type}});return json({url:'/api/files/'+upload[1]},201)}
  const file=url.pathname.match(/^\/api\/files\/([^/]+)$/);if(file&&request.method==='GET'){const obj=await env.BUCKET.get('products/'+file[1]);if(!obj)return new Response('Not found',{status:404});return new Response(obj.body,{headers:{'content-type':obj.httpMetadata?.contentType||'application/octet-stream','cache-control':'private, max-age=86400'}})}
  if(url.pathname==='/api/records'&&request.method==='GET'){const type=url.searchParams.get('type')==='order'?'order':'quote';return json(await listRecords(env.DB,type))}
  if(url.pathname==='/api/records'&&request.method==='POST'){const b=await request.json();if(!b.customer?.trim())return json({error:'El cliente es obligatorio'},400);const count=await env.DB.prepare("SELECT COUNT(*) AS n FROM records WHERE record_type = 'quote'").first();const id=crypto.randomUUID(),number='COT-'+new Date().getFullYear()+'-'+String(Number(count.n)+1).padStart(4,'0'),route=b.selectedRoute==='direct'?'direct':'miami',total=route==='miami'?b.result.landedMiami:b.result.landedDirect;await env.DB.prepare("INSERT INTO records (id,number,record_type,customer_name,phone,description,boxes_json,rates_json,totals_json,products_json,route,total,total_boxes,status,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,number,'quote',b.customer.trim(),b.phone||'',b.description||'',JSON.stringify(b.boxes),JSON.stringify(b.rates),JSON.stringify(b.result),JSON.stringify(b.products||[]),route,total,b.result.totalBoxes,'pending',b.notes||'').run();return json({id,number},201)}
  const promote=url.pathname.match(/^\/api\/records\/([^/]+)\/promote$/);if(promote&&request.method==='POST'){const count=await env.DB.prepare("SELECT COUNT(*) AS n FROM records WHERE record_type = 'order'").first();const number='ORD-'+new Date().getFullYear()+'-'+String(Number(count.n)+1).padStart(4,'0');const out=await env.DB.prepare("UPDATE records SET record_type='order', number=?, status='confirmed', confirmed_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=? AND record_type='quote'").bind(number,promote[1]).run();if(!out.meta.changes)return json({error:'Cotización no encontrada'},404);return json({id:promote[1],number})}
  const revert=url.pathname.match(/^\/api\/records\/([^/]+)\/revert$/);if(revert&&request.method==='POST'){const current=await env.DB.prepare("SELECT number FROM records WHERE id=? AND record_type='order'").bind(revert[1]).first();if(!current)return json({error:'Orden no encontrada'},404);const suffix=String(current.number||'').replace(/^ORD-?/,'')||crypto.randomUUID().slice(0,8),number='COT-R-'+suffix;await env.DB.prepare("UPDATE records SET record_type='quote', number=?, status='returned', confirmed_at=NULL, updated_at=CURRENT_TIMESTAMP WHERE id=? AND record_type='order'").bind(number,revert[1]).run();return json({id:revert[1],number})}
  const item=url.pathname.match(/^\/api\/records\/([^/]+)$/);
  if(item&&request.method==='GET'){const row=await env.DB.prepare("SELECT * FROM records WHERE id=?").bind(item[1]).first();if(!row)return json({error:'Registro no encontrado'},404);return json({...row,boxes:JSON.parse(row.boxes_json),rates:JSON.parse(row.rates_json),totals:JSON.parse(row.totals_json),products:JSON.parse(row.products_json||'[]')})}
  if(item&&request.method==='PATCH'){const b=await request.json();if(b.status){const allowed=['confirmed','purchased','transit','delivered','cancelled'];if(!allowed.includes(b.status))return json({error:'Estado inválido'},400);await env.DB.prepare("UPDATE records SET status=?, updated_at=CURRENT_TIMESTAMP WHERE id=? AND record_type='order'").bind(b.status,item[1]).run()}else{const route=b.route==='direct'?'direct':'miami',total=Number(b.total)||0;const out=await env.DB.prepare("UPDATE records SET customer_name=?, phone=?, description=?, notes=?, route=?, total=?, updated_at=CURRENT_TIMESTAMP WHERE id=? AND record_type='quote'").bind(String(b.customer_name||'').trim(),b.phone||'',b.description||'',b.notes||'',route,total,item[1]).run();if(!out.meta.changes)return json({error:'Solo se pueden editar cotizaciones'},400)}return json({ok:true})}
  if(item&&request.method==='DELETE'){const out=await env.DB.prepare("DELETE FROM records WHERE id=?").bind(item[1]).run();if(!out.meta.changes)return json({error:'Registro no encontrado'},404);return new Response(null,{status:204})}
  return json({error:'Ruta no encontrada'},404)
 }catch(e){return json({error:'No se pudo guardar la información',detail:String(e.message||e)},500)}
}
function staticResponse(path){const item=STATIC[path]||STATIC['/index.html'];if(!item)return new Response('Not found',{status:404});const body=item.base64?Uint8Array.from(atob(item.data),c=>c.charCodeAt(0)):item.data;return new Response(body,{headers:{'content-type':item.type,'cache-control':path==='/index.html'?'no-cache':'public, max-age=31536000, immutable'}})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return handleApi(request,env,url);const path=url.pathname==='/'?'/index.html':url.pathname;return staticResponse(path)}};
