import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Ship,Plane,PackagePlus,Trash2,Settings2,Ruler,ArrowRight,CheckCircle2,Info,Calculator,FileText,ClipboardList,Plus,X,Save,ReceiptText,TrendingUp}from'lucide-react';
import'./style.css';import'./route-breakdown.css';import'./app.css';import{calculate}from'./calculate.js';
import RecordsPage from'./RecordsPage.jsx';
import WeightBreakdown from'./WeightBreakdown.jsx';
import ProductSection,{blankProduct}from'./ProductSection.jsx';
import ProfitPage from'./ProfitPage.jsx';
import'./landed.css';import'./dark.css';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const blank=()=>({id:crypto.randomUUID(),name:'Caja',qty:1,l:12,w:12,h:12,unit:'in',weight:10,weightUnit:'kg'});
const initialRates={cnRate:2,miRate:1.5,cbmRate:550,cnDivisor:5000,miDivisor:166,minCbm:true};
const statusLabel={pending:'Pendiente',confirmed:'Confirmada',purchased:'Comprada',transit:'En tránsito',delivered:'Entregada',cancelled:'Cancelada'};
const statusSteps=['confirmed','purchased','transit','delivered'];
async function api(path,options){const res=await fetch('/api'+path,{headers:{'content-type':'application/json'},...options});if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error([data.error,data.detail].filter(Boolean).join(': ')||'No se pudo completar')}return res.status===204?null:res.json()}
function Field({label,value,onChange,type='number',suffix}){return <label className="field"><span>{label}</span><div><input type={type} step="any" min={type==='number'?0:undefined} value={value} onChange={e=>onChange(e.target.value)}/>{suffix&&<em>{suffix}</em>}</div></label>}
function Nav({page,setPage}){return <nav className="mainNav">{[['calculator',Calculator,'Calcular','Calcular'],['quotes',FileText,'Cotizaciones internas','Internas'],['clientQuotes',ReceiptText,'Cotizaciones para clientes','Clientes'],['profits',TrendingUp,'Ganancias','Ganancias'],['orders',ClipboardList,'Órdenes','Órdenes']].map(([id,Icon,label,short])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/><span className="navFull">{label}</span><span className="navShort">{short}</span></button>)}</nav>}
function SaveDialog({onClose,onSave,result,boxes,rates,products}){const[form,setForm]=useState({customer:'',phone:'',description:'',notes:'',selectedRoute:result.best});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const change=(k,v)=>setForm(x=>({...x,[k]:v}));const landed=form.selectedRoute==='miami'?result.landedMiami:result.landedDirect;async function submit(e){e.preventDefault();setBusy(true);setError('');try{await onSave({...form,boxes,rates,products,result});onClose()}catch(e){setError(e.message||'No se pudo guardar la cotización')}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="dialog" onSubmit={submit}><div className="dialogHead"><div><small>NUEVA COTIZACIÓN</small><h2>Guardar propuesta</h2></div><button type="button" onClick={onClose}><X/></button></div><Field label="Nombre del cliente *" type="text" value={form.customer} onChange={v=>change('customer',v)}/><Field label="Teléfono / WhatsApp" type="text" value={form.phone} onChange={v=>change('phone',v)}/><Field label="Descripción general" type="text" value={form.description} onChange={v=>change('description',v)}/><label className="field"><span>Ruta cotizada</span><select value={form.selectedRoute} onChange={e=>change('selectedRoute',e.target.value)}><option value="miami">Vía 1 · China–Miami–Managua</option><option value="direct">Vía 2 · China–Managua</option></select></label><label className="field"><span>Notas</span><textarea value={form.notes} onChange={e=>change('notes',e.target.value)} placeholder="Condiciones, anticipo, detalles…"/></label><div className="finalMini"><span>Productos + comisión</span><b>{money(result.merchandiseTotal)}</b><span>Envío</span><b>{money(form.selectedRoute==='miami'?result.viaMiami:result.direct)}</b></div><div className="dialogTotal"><span>Total puesto en Nicaragua</span><b>{money(landed)}</b></div>{error&&<div className="saveError" role="alert"><b>No se pudo guardar</b><span>{error}</span></div>}<button className="primary" disabled={!form.customer||busy}><Save/>{busy?'Guardando…':'Guardar cotización'}</button></form></div>}
function CalculatorPage({onSaved}){const[boxes,setBoxes]=useState([blank()]);const[products,setProducts]=useState([blankProduct()]);const[fee,setFee]=useState(3);const[productSummary,setProductSummary]=useState({productSubtotal:0,feePercent:3,feeAmount:0,merchandiseTotal:0,totalUnits:0,landedMiami:0,landedDirect:0,unitMiami:0,unitDirect:0});const[rates,setRates]=useState(initialRates);const[showRates,setShowRates]=useState(false);const[dialog,setDialog]=useState(false);const base=useMemo(()=>calculate(boxes,rates),[boxes,rates]);const r={...base,...productSummary};const upd=(id,k,v)=>setBoxes(x=>x.map(b=>b.id===id?{...b,[k]:v}:b));const rr=(k,v)=>setRates(x=>({...x,[k]:v}));async function save(data){await api('/records',{method:'POST',body:JSON.stringify(data)});onSaved()}
return <div className="workspace"><div className="pageHead"><div><small>NUEVA COTIZACIÓN</small><h1>Calculadora logística</h1><p>Compara las dos vías y guarda la propuesta del cliente.</p></div><button className="settings" onClick={()=>setShowRates(!showRates)}><Settings2/> Tarifas</button></div>{showRates&&<section className="panel rates"><div className="sectionTitle"><div><span>$</span><h2>Tarifas y reglas</h2></div></div><div className="rateGrid"><Field label="China → Miami" value={rates.cnRate} onChange={v=>rr('cnRate',v)} suffix="$/kg"/><Field label="Miami → Managua" value={rates.miRate} onChange={v=>rr('miRate',v)} suffix="$/lb"/><Field label="China → Managua" value={rates.cbmRate} onChange={v=>rr('cbmRate',v)} suffix="$/CBM"/><Field label="Divisor China" value={rates.cnDivisor} onChange={v=>rr('cnDivisor',v)}/><Field label="Divisor Miami" value={rates.miDivisor} onChange={v=>rr('miDivisor',v)}/></div><label className="toggle"><input type="checkbox" checked={rates.minCbm} onChange={e=>rr('minCbm',e.target.checked)}/><span/>Cobrar mínimo 1 CBM en ruta directa</label></section>}
<section className="panel"><div className="sectionTitle"><div><span>01</span><h2>Carga</h2></div><p>{r.totalBoxes} cajas</p></div><div className="boxes">{boxes.map((b,i)=><article className="box" key={b.id}><div className="boxTop"><b><PackagePlus/> Caja {i+1}</b>{boxes.length>1&&<button onClick={()=>setBoxes(x=>x.filter(v=>v.id!==b.id))}><Trash2/></button>}</div><div className="grid"><Field label="Cantidad" value={b.qty} onChange={v=>upd(b.id,'qty',v)}/><Field label="Largo" value={b.l} onChange={v=>upd(b.id,'l',v)}/><Field label="Ancho" value={b.w} onChange={v=>upd(b.id,'w',v)}/><Field label="Alto" value={b.h} onChange={v=>upd(b.id,'h',v)}/><label className="field"><span>Medidas</span><select value={b.unit} onChange={e=>upd(b.id,'unit',e.target.value)}><option value="in">Pulgadas</option><option value="cm">Centímetros</option></select></label><Field label="Peso/caja" value={b.weight} onChange={v=>upd(b.id,'weight',v)}/><label className="field"><span>Unidad peso</span><select value={b.weightUnit} onChange={e=>upd(b.id,'weightUnit',e.target.value)}><option value="kg">Kilogramos</option><option value="lb">Libras</option></select></label></div></article>)}</div><button className="add" onClick={()=>setBoxes(x=>[...x,blank()])}><Plus/> Agregar otro tipo de caja</button></section>
<ProductSection products={products} setProducts={setProducts} fee={fee} setFee={setFee} shipping={{viaMiami:r.viaMiami,direct:r.direct,onSummary:setProductSummary}}/><section className="results"><div className="resultHead"><span>03</span><div><h2>Costo puesto en Nicaragua</h2><p>Productos, comisión y envío incluidos</p></div></div><div className="routeGrid"><RouteOne r={r} rates={rates}/><RouteTwo r={r} rates={rates}/></div><div className="landedGrid"><div><span>Con Vía 1</span><b>{money(r.landedMiami)}</b><small>{r.totalUnits?money(r.unitMiami)+' por unidad':'Agrega cantidades'}</small></div><div><span>Con Vía 2</span><b>{money(r.landedDirect)}</b><small>{r.totalUnits?money(r.unitDirect)+' por unidad':'Agrega cantidades'}</small></div></div><div className="verdict"><CheckCircle2/><div><small>RECOMENDACIÓN</small><h2>{r.best==='miami'?'Vía 1 · China–Miami–Managua':'Vía 2 · China–Managua'}</h2><p>Ahorro estimado: <b>{money(r.saving)}</b></p></div><button className="saveQuote" onClick={()=>setDialog(true)}><Save/> Guardar cotización</button></div><div className="capacity"><div><span><Ruler/> APROVECHAMIENTO DEL CBM</span><b>{Math.min(100,r.cbm*100).toFixed(1)}%</b></div><div className="bar"><i style={{width:`${Math.min(100,r.cbm*100)}%`}}/></div><p><Info/> {r.cbm<1?<>Quedan <b>{r.space.toFixed(3)} CBM</b>. Puedes agregar aproximadamente <b>{r.more} cajas similares</b>.</>:<>La carga ocupa <b>{r.cbm.toFixed(3)} CBM</b>.</>}</p></div></section>{dialog&&<SaveDialog onClose={()=>setDialog(false)} onSave={save} result={r} boxes={boxes} rates={rates} products={products}/>}</div>}
function RouteOne({r,rates}){return <article className={'route '+(r.best==='miami'?'winner':'')}><div className="routeIcon"><Plane/></div><div><small>VÍA 1 · DOS TRAYECTOS</small><h3>China <ArrowRight/> Miami <ArrowRight/> Managua</h3></div>{r.best==='miami'&&<mark>Recomendada</mark>}<WeightBreakdown r={r}/><dl className="legs"><div><dt><b>1. China → Miami</b><span>{r.cnBillKg.toFixed(2)} kg facturables × {money(rates.cnRate)}</span></dt><dd>{money(r.cnCost)}</dd></div><div><dt><b>2. Miami → Managua</b><span>{r.miBillLb.toFixed(2)} lb facturables × {money(rates.miRate)}</span></dt><dd>{money(r.miCost)}</dd></div></dl><div className="routeTotal"><span>TOTAL VÍA 1</span><strong>{money(r.viaMiami)}</strong></div></article>}
function RouteTwo({r,rates}){return <article className={'route '+(r.best==='direct'?'winner':'')}><div className="routeIcon ship"><Ship/></div><div><small>VÍA 2 · DIRECTA</small><h3>China <ArrowRight/> Managua</h3></div>{r.best==='direct'&&<mark>Recomendada</mark>}<dl className="legs"><div><dt><b>China → Managua</b><span>{r.billCbm.toFixed(3)} CBM × {money(rates.cbmRate)}</span></dt><dd>{money(r.direct)}</dd></div><div><dt>Volumen real</dt><dd>{r.cbm.toFixed(3)} CBM</dd></div></dl><div className="routeTotal"><span>TOTAL VÍA 2</span><strong>{money(r.direct)}</strong></div></article>}
function App(){const[page,setPage]=useState('calculator'),[refresh,setRefresh]=useState(0);function saved(){setRefresh(x=>x+1);setPage('quotes')}const recordType=page==='quotes'?'quote':page==='clientQuotes'?'client':'order';return <><header><div className="brand"><div className="logo"><Ship/></div><div><b>RutaSmart</b><small>Cotizaciones y órdenes</small></div></div><Nav page={page} setPage={setPage}/></header><main className="appMain">{page==='calculator'?<CalculatorPage onSaved={saved}/>:page==='profits'?<ProfitPage refreshKey={refresh}/>:<RecordsPage type={recordType} refreshKey={refresh} onChange={()=>setRefresh(x=>x+1)}/>}</main></>}
createRoot(document.getElementById('root')).render(<App/>);
