import React from'react';import{Plus,Trash2,ImagePlus,PackageOpen}from'lucide-react';import'./products.css';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const blank=()=>({id:crypto.randomUUID(),name:'',price:0,qty:1,imageUrl:'',uploading:false});
export default function ProductSection({products,setProducts,fee,setFee,shipping}){
 const subtotal=products.reduce((s,p)=>s+(Number(p.price)||0)*(Number(p.qty)||0),0),feeAmount=subtotal*Number(fee||0)/100,totalProducts=subtotal+feeAmount,units=products.reduce((s,p)=>s+(Number(p.qty)||0),0);
 const update=(id,k,v)=>setProducts(x=>x.map(p=>p.id===id?{...p,[k]:v}:p));
 async function upload(id,file){if(!file)return;if(file.size>5*1024*1024){alert('La foto debe pesar menos de 5 MB');return}update(id,'uploading',true);try{const key=crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const r=await fetch('/api/uploads/'+key,{method:'PUT',headers:{'content-type':file.type||'application/octet-stream'},body:file});if(!r.ok)throw new Error();update(id,'imageUrl','/api/files/'+key)}catch{alert('No se pudo subir la foto')}finally{update(id,'uploading',false)}}
 React.useEffect(()=>{shipping.onSummary({productSubtotal:subtotal,feePercent:Number(fee||0),feeAmount,merchandiseTotal:totalProducts,totalUnits:units,landedMiami:totalProducts+shipping.viaMiami,landedDirect:totalProducts+shipping.direct,unitMiami:units?(totalProducts+shipping.viaMiami)/units:0,unitDirect:units?(totalProducts+shipping.direct)/units:0})},[subtotal,feeAmount,totalProducts,units,shipping.viaMiami,shipping.direct]);
 return <section className="panel productPanel"><div className="sectionTitle"><div><span>02</span><h2>Productos</h2></div><p>{units} unidades</p></div><p className="sectionHelp">Agrega lo que vas a comprar. La comisión de compra se calcula automáticamente.</p><div className="productList">{products.map((p,i)=><article className="productRow" key={p.id}><label className="photoPicker">{p.imageUrl?<img src={p.imageUrl} alt=""/>:<><ImagePlus/><span>{p.uploading?'Subiendo…':'Foto'}</span></>}<input type="file" accept="image/*" onChange={e=>upload(p.id,e.target.files[0])}/></label><label><span>Producto</span><input value={p.name} onChange={e=>update(p.id,'name',e.target.value)} placeholder={'Producto '+(i+1)}/></label><label><span>Precio unitario</span><input type="number" min="0" step="any" value={p.price} onChange={e=>update(p.id,'price',e.target.value)}/></label><label><span>Cantidad</span><input type="number" min="1" value={p.qty} onChange={e=>update(p.id,'qty',e.target.value)}/></label><div className="productLineTotal"><span>Subtotal</span><b>{money(Number(p.price)*Number(p.qty))}</b></div>{products.length>1&&<button className="removeProduct" onClick={()=>setProducts(x=>x.filter(v=>v.id!==p.id))}><Trash2/></button>}</article>)}</div><button className="add" onClick={()=>setProducts(x=>[...x,blank()])}><Plus/> Agregar producto</button><div className="purchaseSummary"><div><span>Subtotal mercancía</span><b>{money(subtotal)}</b></div><label><span>Comisión de compra</span><div><input type="number" min="0" step="any" value={fee} onChange={e=>setFee(e.target.value)}/><em>%</em></div></label><div><span>Comisión ({fee}%)</span><b>{money(feeAmount)}</b></div><div className="purchaseTotal"><span>Total de productos</span><strong>{money(totalProducts)}</strong></div></div></section>
}
export{blank as blankProduct};
