import React,{useEffect,useState}from'react';
import{Search,FileText,CheckCircle2,X,Pencil,Trash2,Phone,Package,Route,CalendarDays,StickyNote,Printer,Plus}from'lucide-react';
import'./detail.css';
import'./product-detail.css';

const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const labels={pending:'Pendiente',returned:'Archivada',confirmed:'Confirmada',purchased:'Comprada',transit:'En tránsito',delivered:'Entregada',cancelled:'Cancelada'};
const steps=['confirmed','purchased','transit','delivered'];
async function api(path,options){const r=await fetch('/api'+path,{headers:{'content-type':'application/json'},...options});if(!r.ok)throw new Error((await r.json()).error||'No se pudo completar');return r.status===204?null:r.json()}
const boxCbm=b=>Number(b.l||0)*Number(b.w||0)*Number(b.h||0)*(b.unit==='cm'?0.000001:0.000016387064);
const productLogistics=(data,product)=>{const boxes=(data.boxes||[]).filter(b=>b.productId===product.id||(!b.productId&&b.productName===product.name)),boxCount=boxes.reduce((sum,b)=>sum+Number(b.qty||0),0),totalCbm=boxes.reduce((sum,b)=>sum+boxCbm(b)*Number(b.qty||0),0);return{boxCount,totalCbm,unitCbm:Number(product.qty||0)>0?totalCbm/Number(product.qty):0}};

function ClientQuote({data,onClose,onConfirmed,onDeleted}){
 const total=Number(data.totals?.saleTotal??Number(data.total||0)*1.30),totalUnits=Number(data.totals?.totalUnits||0),totalBoxes=Number(data.total_boxes??(data.boxes||[]).reduce((sum,b)=>sum+Number(b.qty||0),0)),totalCbm=Number(data.totals?.cbm??(data.boxes||[]).reduce((sum,b)=>sum+boxCbm(b)*Number(b.qty||0),0));
 async function confirmQuote(){if(!window.confirm('¿El cliente confirmó esta cotización? Se registrará en Órdenes.'))return;await api(`/records/${data.id}/promote`,{method:'POST'});onConfirmed();onClose()}
 async function deleteQuote(){if(!window.confirm('¿Eliminar esta cotización? También se borrará de Cotizaciones internas. Esta acción no se puede deshacer.'))return;await api(`/records/${data.id}`,{method:'DELETE'});onDeleted();onClose()}
 return <div className="clientQuoteOverlay"><section className="clientQuotePrint">
  <div className="clientQuoteTools"><button onClick={onClose}><X/> Cerrar</button><button className="clientDelete" onClick={deleteQuote}><Trash2/> Eliminar</button><button className="clientConfirmed" onClick={confirmQuote}><CheckCircle2/> Cliente confirmó</button><button className="printQuote" onClick={()=>window.print()}><Printer/> Imprimir / guardar PDF</button></div>
  <header className="clientQuoteHeader"><div className="quoteBrand"><span>CC</span><div><b>CotizacionesChina</b><small>Compras y logística internacional</small></div></div><div className="quoteTitle"><small>COTIZACIÓN PARA CLIENTE</small><strong>{data.number}</strong></div></header>
  <div className="clientQuoteMeta"><div><small>PREPARADA PARA</small><strong>{data.customer_name}</strong>{data.phone&&<span>{data.phone}</span>}</div><div><small>FECHA</small><strong>{new Date(data.created_at).toLocaleDateString('es-NI',{year:'numeric',month:'long',day:'numeric'})}</strong><span>Entrega en Managua, Nicaragua</span></div></div>
  <div className="clientProductTableWrap"><div className="clientProductTable"><div className="clientProductHead clientProductLogistics"><span>Producto</span><span>Unidades</span><span>Cajas</span><span>CBM/unidad</span><span>CBM total</span><span>Precio</span><span>Subtotal</span></div>{data.products?.length?<>{data.products.map((p,i)=>{const logistics=productLogistics(data,p);return <div className="clientProductRow clientProductLogistics" key={p.id||i}><div className="clientProductCell">{p.imageUrl?<img className="clientProductPhoto" src={p.imageUrl} alt={p.name||'Producto'}/>:<span className="clientProductNoPhoto">Sin foto</span>}<b>{p.name||'Producto'}</b></div><b>{Number(p.qty||0).toLocaleString()}</b><b>{logistics.boxCount.toLocaleString()}</b><b>{logistics.unitCbm.toFixed(6)}</b><b>{logistics.totalCbm.toFixed(4)}</b><b>{money(p.salePrice??p.price)}</b><b>{money(Number(p.qty||0)*Number((p.salePrice??p.price)||0))}</b></div>})}</>:<div className="clientProductRow"><span>{data.description||'Productos cotizados'}</span><b>{totalUnits.toLocaleString()}</b></div>}</div></div>
  <div className="clientQuoteSummary"><div><span>Total de unidades</span><b>{totalUnits.toLocaleString()}</b></div><div><span>Total de cajas</span><b>{totalBoxes.toLocaleString()}</b></div><div><span>CBM total</span><b>{totalCbm.toFixed(4)} m³</b></div><div className="clientGrandTotal"><span>Total puesto en Managua<br/><small>Incluyendo envío</small></span><strong>{money(total)}</strong></div></div>
  <div className="clientQuoteNotes"><b>Servicio incluido</b><p>Compra, gestión logística y envío de los productos hasta Managua, Nicaragua.</p></div>
  <footer><span>Gracias por confiar en CotizacionesChina.</span><b>Cotización válida sujeta a confirmación de disponibilidad.</b></footer>
 </section></div>
}

function ClientDetail({id,onClose,onConfirmed,onDeleted}){
 const[data,setData]=useState(null);
 useEffect(()=>{api('/records/'+id).then(setData)},[id]);
 if(!data)return <div className="overlay"><div className="detailSheet loadingDetail">Preparando cotización para el cliente…</div></div>;
 return <ClientQuote data={data} onClose={onClose} onConfirmed={onConfirmed} onDeleted={onDeleted}/>;
}

function Detail({id,type,onClose,onChanged}){
 const[data,setData]=useState(null),[edit,setEdit]=useState(false),[form,setForm]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/records/'+id).then(x=>{setData(x);setForm({...x})})},[id]);
 if(!data)return <div className="overlay"><div className="detailSheet loadingDetail">Cargando expediente…</div></div>;
 const totals=data.totals,shownRoute=edit?form.route:data.route,selectedShipping=shownRoute==='miami'?totals.viaMiami:totals.direct,routeTotal=shownRoute==='miami'?(totals.landedMiami??totals.viaMiami):(totals.landedDirect??totals.direct),hasSalePrices=data.products?.some(p=>Number(p.salePrice)>0),productSubtotal=Number(totals.productSubtotal)||data.products?.reduce((sum,p)=>sum+Number(p.qty||0)*Number(p.price||0),0)||0,landedFactor=productSubtotal>0?Number(data.total||routeTotal)/productSubtotal:0;
 const f=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(){setBusy(true);try{await api('/records/'+id,{method:'PATCH',body:JSON.stringify({...form,total:routeTotal})});setData({...data,...form,total:routeTotal});setEdit(false);onChanged()}finally{setBusy(false)}}
 async function remove(){const isOrder=data.record_type==='order',message=isOrder?'¿Quitar esta orden? Se conservará en Cotizaciones internas y Cotizaciones para clientes.':'¿Eliminar esta cotización permanentemente? Esta acción no se puede deshacer.';if(!confirm(message))return;setBusy(true);try{await api('/records/'+id+(isOrder?'/revert':''),{method:isOrder?'POST':'DELETE'});onChanged();onClose()}finally{setBusy(false)}}
 return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="detailSheet">
  <div className="detailTop"><div><span className={'badge '+data.status}>{labels[data.status]}</span><small>{data.record_type==='quote'?'EXPEDIENTE DE COTIZACIÓN':'EXPEDIENTE DE ORDEN'}</small><h2>{data.number}</h2></div><button className="iconBtn" onClick={onClose}><X/></button></div>
  <div className="detailActions">{!edit&&<>{type==='quote'&&<button onClick={()=>setEdit(true)}><Pencil/> Editar</button>}<button className="danger" disabled={busy} onClick={remove}><Trash2/> {type==='order'?'Quitar de órdenes':'Eliminar'}</button></>}</div>
  <div className="quoteUnifiedCard">
  <div className="detailGrid"><div className="detailCard"><label>Cliente</label>{edit?<input value={form.customer_name} onChange={e=>f('customer_name',e.target.value)}/>:<b>{data.customer_name}</b>}<span><Phone/> {edit?<input value={form.phone} onChange={e=>f('phone',e.target.value)}/>:data.phone||'Sin teléfono'}</span></div><div className="detailCard"><label>Cotización</label>{edit?<input value={form.description} onChange={e=>f('description',e.target.value)}/>:<b>{data.description||'Sin descripción'}</b>}<span><CalendarDays/> Creada {new Date(data.created_at).toLocaleString()}</span></div></div>
  <div className="detailGroupLabel"><span>01</span><div><b>Información de productos</b><small>Productos, precios, cantidades y cajas</small></div></div>
	  {data.products?.length>0&&<div className="internalProductTableWrap"><div className="internalProductTable"><div className="internalProductHead"><span>Producto</span><span>Unidades</span><span>Costo puesto/u</span><span>Venta/u</span><span>Cajas</span><span>Información de caja</span><span>Compra</span></div>{data.products.map((p,i)=>{const boxes=(data.boxes||[]).filter(b=>b.productId===p.id||(!b.productId&&b.productName===p.name)),box=boxes[0]||{},boxCount=boxes.reduce((sum,b)=>sum+Number(b.qty||0),0),landedUnit=Number(p.price||0)*landedFactor;return <div className="internalProductRow" key={p.id||i}><div className="internalProductIdentity">{p.imageUrl?<img src={p.imageUrl} alt={p.name||'Producto'}/>:<span className="noPhoto">Sin foto</span>}<b>{p.name||'Producto'}</b></div><span>{Number(p.qty||0).toLocaleString()}</span><b>{money(landedUnit)}</b><b className="salePriceValue">{Number(p.salePrice)>0?money(p.salePrice):'—'}</b><span>{boxCount.toLocaleString()}</span><span>{box.l?`${box.l} × ${box.w} × ${box.h} ${box.unit} · ${box.weight} ${box.weightUnit} · ${box.unitsPerBox||'—'}/caja`:'Sin caja'}</span><b>{money(Number(p.qty)*Number(p.price))}</b></div>})}</div><p className="unitPriceNote">El costo puesto por unidad incluye producto, comisión y envío distribuido proporcionalmente.</p></div>}
  <div className="detailGroupLabel shippingGroup"><span>02</span><div><b>Información de envío</b><small>Ruta, peso facturable y total puesto en Nicaragua</small></div></div>
	  <div className="internalShippingSummary"><div><small>RUTA SELECCIONADA</small>{edit?<select value={form.route} onChange={e=>f('route',e.target.value)}><option value="miami">Vía 1 · China–Miami–Managua</option><option value="direct">Vía 2 · China–Managua</option></select>:<b className="chosenRoute">{shownRoute==='miami'?'Vía 1 · China → Miami → Managua':'Vía 2 · China → Managua'}</b>}<span>{shownRoute==='miami'?`China–Miami ${money(totals.cnCost)} · Miami–Managua ${money(totals.miCost)}`:`China–Managua ${money(totals.direct)}`}</span></div><div className="shippingMetric"><small>CBM TOTAL</small><b>{Number(totals.cbm||0).toFixed(4)} m³</b></div><div className="shippingMetric"><small>PESO TOTAL</small><b>{Number(totals.actualKg||0).toFixed(2)} kg</b><span>{Number(totals.actualLb||0).toFixed(2)} lb</span></div><div className="shippingMetric"><small>ENVÍO</small><b>{money(selectedShipping)}</b>{shownRoute==='miami'&&<span>Cobro: {Number(totals.cnBillKg||0).toFixed(2)} kg / {Number(totals.miBillLb||0).toFixed(2)} lb</span>}</div></div>
	  {data.products?.length>0&&<div className="internalTotalsSummary"><div><span>Subtotal productos</span><b>{money(totals.productSubtotal)}</b></div><div><span>Comisión ({totals.feePercent}%)</span><b>{money(totals.feeAmount)}</b></div><div><span>Productos + comisión</span><b>{money(totals.merchandiseTotal)}</b></div><div><span>Envío seleccionado</span><b>{money(selectedShipping)}</b></div><div className="internalGrandTotal"><span>Total puesto en Nicaragua</span><strong>{money(edit?routeTotal:data.total)}</strong></div><div className="internalUnitTotal"><span>Costo promedio por unidad</span><strong>{money(shownRoute==='miami'?totals.unitMiami:totals.unitDirect)}</strong></div></div>}
	  <div className="internalNotes"><h3><StickyNote/> Notas</h3>{edit?<textarea value={form.notes} onChange={e=>f('notes',e.target.value)}/>:<p>{data.notes||'Sin notas'}</p>}</div>
  </div>
  {edit&&<div className="editFooter"><button onClick={()=>{setEdit(false);setForm({...data})}}>Cancelar</button><button className="primary" disabled={!form.customer_name||busy} onClick={save}>{busy?'Guardando…':'Guardar cambios'}</button></div>}
 </section></div>
}

export default function RecordsPage({type,refreshKey,onChange,onCreateQuote}){
 const[rows,setRows]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null);
 const isClient=type==='client',recordType=isClient?'quote':type;
 async function load(){setLoading(true);try{setRows(await api(`/records?type=${recordType}`))}finally{setLoading(false)}}
 useEffect(()=>{load()},[type,refreshKey]);
 const filtered=rows.filter(x=>(x.customer_name+' '+x.number+' '+(x.description||'')).toLowerCase().includes(query.toLowerCase()));
 async function promote(e,id){e.stopPropagation();await api(`/records/${id}/promote`,{method:'POST'});load();onChange()}
 async function status(e,id){e.stopPropagation();await api(`/records/${id}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})});load()}
 async function removeRow(e,id){e.stopPropagation();if(!window.confirm('¿Quitar esta orden? Se conservará en Cotizaciones internas y Cotizaciones para clientes.'))return;await api(`/records/${id}/revert`,{method:'POST'});load();onChange()}
 async function deleteClientQuote(e,id){e.stopPropagation();if(!window.confirm('¿Eliminar esta cotización? También se borrará de Cotizaciones internas. Esta acción no se puede deshacer.'))return;await api(`/records/${id}`,{method:'DELETE'});load();onChange()}
 return <div className="workspace"><div className="pageHead"><div><small>{isClient?'DOCUMENTOS PARA ENVIAR':type==='quote'?'VENTAS':'LOGÍSTICA'}</small><h1>{isClient?'Cotizaciones para clientes':type==='quote'?'Cotizaciones internas':'Órdenes en proceso'}</h1><p>{isClient?'Precios finales con ganancia y envío incluidos, listos para imprimir.':type==='quote'?'Edita, revisa o confirma cada propuesta.':'Abre una orden para ver, actualizar o eliminar su expediente.'}</p></div>{isClient&&<button className="newClientQuote" onClick={onCreateQuote}><Plus/> Crear cotización</button>}</div>
 <div className="stats"><div><span>Total</span><b>{rows.length}</b></div><div><span>{type==='order'?'En proceso':'Pendientes'}</span><b>{rows.filter(x=>type==='order'?x.status!=='delivered':x.status==='pending').length}</b></div><div><span>{isClient?'Valor de venta':'Valor'}</span><b>{money(rows.reduce((s,x)=>s+(isClient?Number(x.totals?.saleTotal??x.total*1.30):Number(x.total)),0))}</b></div></div>
 <section className="panel records"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente o número…"/></div>{loading?<div className="empty">Cargando…</div>:filtered.length===0?<div className="empty"><FileText/><h3>No hay registros</h3><p>{type==='order'?'Las cotizaciones confirmadas aparecerán aquí.':'Crea una cotización desde la sección Calcular.'}</p></div>:<div className="recordList">{filtered.map(x=>{const shownTotal=isClient?Number(x.totals?.saleTotal??x.total*1.30):Number(x.total);return <article className="record clickable" key={x.id} onClick={()=>setSelected(x.id)}><div className="recordMain"><span className={'badge '+x.status}>{labels[x.status]}</span><b>{x.number}</b><h3>{x.customer_name}</h3><p>{x.description||'Sin descripción'} · {x.total_boxes} cajas{isClient?' · Envío incluido':' · '+(x.route==='miami'?'Vía Miami':'Vía directa')}</p></div><div className="recordSide"><strong>{money(shownTotal)}</strong><small>{new Date(x.created_at).toLocaleDateString()}</small>{isClient?<div className="clientRowActions"><button className="confirm" onClick={e=>promote(e,x.id)}><CheckCircle2/> Cliente confirmó</button><button className="clientRowDelete" onClick={e=>deleteClientQuote(e,x.id)}><Trash2/> Eliminar</button></div>:type==='quote'?<button className="confirm" onClick={e=>promote(e,x.id)}><CheckCircle2/> Cliente confirmó</button>:type==='order'?<div className="orderRowActions"><select value={x.status} onClick={e=>e.stopPropagation()} onChange={e=>status(e,x.id)}>{steps.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select><button className="orderDelete" onClick={e=>removeRow(e,x.id)}><Trash2/> Quitar</button></div>:<span className="readyToSend"><Printer/> Lista para imprimir</span>}</div></article>})}</div>}</section>
 {selected&&(isClient?<ClientDetail id={selected} onClose={()=>setSelected(null)} onConfirmed={()=>{load();onChange()}} onDeleted={()=>{load();onChange()}}/>:<Detail id={selected} type={type} onClose={()=>setSelected(null)} onChanged={()=>{load();onChange()}}/>)}</div>
}
